package com.tianfang.evaluat.pojo;

import java.util.Date;

public class EvaluatResult {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_result.id
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_result.user_id
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_result.eva_id
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    private String evaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_result.eva_score_id
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    private String evaScoreId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_result.sum_score
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    private Integer sumScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_result.create_time
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_result.last_update_time
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_result.stat
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_result.id
     *
     * @return the value of sst_evaluat_result.id
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_result.id
     *
     * @param id the value for sst_evaluat_result.id
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_result.user_id
     *
     * @return the value of sst_evaluat_result.user_id
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_result.user_id
     *
     * @param userId the value for sst_evaluat_result.user_id
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_result.eva_id
     *
     * @return the value of sst_evaluat_result.eva_id
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    public String getEvaId() {
        return evaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_result.eva_id
     *
     * @param evaId the value for sst_evaluat_result.eva_id
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    public void setEvaId(String evaId) {
        this.evaId = evaId == null ? null : evaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_result.eva_score_id
     *
     * @return the value of sst_evaluat_result.eva_score_id
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    public String getEvaScoreId() {
        return evaScoreId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_result.eva_score_id
     *
     * @param evaScoreId the value for sst_evaluat_result.eva_score_id
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    public void setEvaScoreId(String evaScoreId) {
        this.evaScoreId = evaScoreId == null ? null : evaScoreId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_result.sum_score
     *
     * @return the value of sst_evaluat_result.sum_score
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    public Integer getSumScore() {
        return sumScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_result.sum_score
     *
     * @param sumScore the value for sst_evaluat_result.sum_score
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    public void setSumScore(Integer sumScore) {
        this.sumScore = sumScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_result.create_time
     *
     * @return the value of sst_evaluat_result.create_time
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_result.create_time
     *
     * @param createTime the value for sst_evaluat_result.create_time
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_result.last_update_time
     *
     * @return the value of sst_evaluat_result.last_update_time
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_result.last_update_time
     *
     * @param lastUpdateTime the value for sst_evaluat_result.last_update_time
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_result.stat
     *
     * @return the value of sst_evaluat_result.stat
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_result.stat
     *
     * @param stat the value for sst_evaluat_result.stat
     *
     * @mbggenerated Tue Feb 02 15:29:11 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}