package com.tianfang.evaluat.pojo;

import java.util.Date;

public class EvaluatQuestion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_question.id
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_question.eva_id
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    private String evaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_question.title
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_question.sum_score
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    private Integer sumScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_question.order_by
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    private Integer orderBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_question.create_time
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_question.last_update_time
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_question.stat
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_question.id
     *
     * @return the value of sst_evaluat_question.id
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_question.id
     *
     * @param id the value for sst_evaluat_question.id
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_question.eva_id
     *
     * @return the value of sst_evaluat_question.eva_id
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public String getEvaId() {
        return evaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_question.eva_id
     *
     * @param evaId the value for sst_evaluat_question.eva_id
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public void setEvaId(String evaId) {
        this.evaId = evaId == null ? null : evaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_question.title
     *
     * @return the value of sst_evaluat_question.title
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_question.title
     *
     * @param title the value for sst_evaluat_question.title
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_question.sum_score
     *
     * @return the value of sst_evaluat_question.sum_score
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public Integer getSumScore() {
        return sumScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_question.sum_score
     *
     * @param sumScore the value for sst_evaluat_question.sum_score
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public void setSumScore(Integer sumScore) {
        this.sumScore = sumScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_question.order_by
     *
     * @return the value of sst_evaluat_question.order_by
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public Integer getOrderBy() {
        return orderBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_question.order_by
     *
     * @param orderBy the value for sst_evaluat_question.order_by
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public void setOrderBy(Integer orderBy) {
        this.orderBy = orderBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_question.create_time
     *
     * @return the value of sst_evaluat_question.create_time
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_question.create_time
     *
     * @param createTime the value for sst_evaluat_question.create_time
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_question.last_update_time
     *
     * @return the value of sst_evaluat_question.last_update_time
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_question.last_update_time
     *
     * @param lastUpdateTime the value for sst_evaluat_question.last_update_time
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_question.stat
     *
     * @return the value of sst_evaluat_question.stat
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_question.stat
     *
     * @param stat the value for sst_evaluat_question.stat
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}