package com.tianfang.evaluat.pojo;

import java.util.Date;

public class EvaluatScore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_score.id
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_score.eva_id
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    private String evaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_score.start_score
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    private Integer startScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_score.end_score
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    private Integer endScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_score.abstracts
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    private String abstracts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_score.create_time
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_score.last_update_time
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_evaluat_score.stat
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_score.id
     *
     * @return the value of sst_evaluat_score.id
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_score.id
     *
     * @param id the value for sst_evaluat_score.id
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_score.eva_id
     *
     * @return the value of sst_evaluat_score.eva_id
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public String getEvaId() {
        return evaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_score.eva_id
     *
     * @param evaId the value for sst_evaluat_score.eva_id
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public void setEvaId(String evaId) {
        this.evaId = evaId == null ? null : evaId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_score.start_score
     *
     * @return the value of sst_evaluat_score.start_score
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public Integer getStartScore() {
        return startScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_score.start_score
     *
     * @param startScore the value for sst_evaluat_score.start_score
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public void setStartScore(Integer startScore) {
        this.startScore = startScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_score.end_score
     *
     * @return the value of sst_evaluat_score.end_score
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public Integer getEndScore() {
        return endScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_score.end_score
     *
     * @param endScore the value for sst_evaluat_score.end_score
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public void setEndScore(Integer endScore) {
        this.endScore = endScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_score.abstracts
     *
     * @return the value of sst_evaluat_score.abstracts
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public String getAbstracts() {
        return abstracts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_score.abstracts
     *
     * @param abstracts the value for sst_evaluat_score.abstracts
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public void setAbstracts(String abstracts) {
        this.abstracts = abstracts == null ? null : abstracts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_score.create_time
     *
     * @return the value of sst_evaluat_score.create_time
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_score.create_time
     *
     * @param createTime the value for sst_evaluat_score.create_time
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_score.last_update_time
     *
     * @return the value of sst_evaluat_score.last_update_time
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_score.last_update_time
     *
     * @param lastUpdateTime the value for sst_evaluat_score.last_update_time
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_evaluat_score.stat
     *
     * @return the value of sst_evaluat_score.stat
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_evaluat_score.stat
     *
     * @param stat the value for sst_evaluat_score.stat
     *
     * @mbggenerated Fri Jan 29 17:27:29 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}