package com.tianfang.train.mapper;

import com.tianfang.train.pojo.CompetitionNews;
import com.tianfang.train.pojo.CompetitionNewsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompetitionNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_competition_news
     *
     * @mbggenerated Wed Feb 03 10:19:44 CST 2016
     */
    int countByExample(CompetitionNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_competition_news
     *
     * @mbggenerated Wed Feb 03 10:19:44 CST 2016
     */
    int deleteByExample(CompetitionNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_competition_news
     *
     * @mbggenerated Wed Feb 03 10:19:44 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_competition_news
     *
     * @mbggenerated Wed Feb 03 10:19:44 CST 2016
     */
    int insert(CompetitionNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_competition_news
     *
     * @mbggenerated Wed Feb 03 10:19:44 CST 2016
     */
    int insertSelective(CompetitionNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_competition_news
     *
     * @mbggenerated Wed Feb 03 10:19:44 CST 2016
     */
    List<CompetitionNews> selectByExample(CompetitionNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_competition_news
     *
     * @mbggenerated Wed Feb 03 10:19:44 CST 2016
     */
    CompetitionNews selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_competition_news
     *
     * @mbggenerated Wed Feb 03 10:19:44 CST 2016
     */
    int updateByExampleSelective(@Param("record") CompetitionNews record, @Param("example") CompetitionNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_competition_news
     *
     * @mbggenerated Wed Feb 03 10:19:44 CST 2016
     */
    int updateByExample(@Param("record") CompetitionNews record, @Param("example") CompetitionNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_competition_news
     *
     * @mbggenerated Wed Feb 03 10:19:44 CST 2016
     */
    int updateByPrimaryKeySelective(CompetitionNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_competition_news
     *
     * @mbggenerated Wed Feb 03 10:19:44 CST 2016
     */
    int updateByPrimaryKey(CompetitionNews record);
}