package com.tianfang.train.mapper;

import com.tianfang.train.pojo.MatchPlayerBaseDatas;
import com.tianfang.train.pojo.MatchPlayerBaseDatasExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MatchPlayerBaseDatasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    int countByExample(MatchPlayerBaseDatasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    int deleteByExample(MatchPlayerBaseDatasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    int insert(MatchPlayerBaseDatas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    int insertSelective(MatchPlayerBaseDatas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    List<MatchPlayerBaseDatas> selectByExample(MatchPlayerBaseDatasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    MatchPlayerBaseDatas selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    int updateByExampleSelective(@Param("record") MatchPlayerBaseDatas record, @Param("example") MatchPlayerBaseDatasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    int updateByExample(@Param("record") MatchPlayerBaseDatas record, @Param("example") MatchPlayerBaseDatasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    int updateByPrimaryKeySelective(MatchPlayerBaseDatas record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    int updateByPrimaryKey(MatchPlayerBaseDatas record);
}