package com.tianfang.train.mapper;

import com.tianfang.train.pojo.TeamResult;
import com.tianfang.train.pojo.TeamResultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeamResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_team_result
     *
     * @mbggenerated Wed Jan 27 10:58:26 CST 2016
     */
    int countByExample(TeamResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_team_result
     *
     * @mbggenerated Wed Jan 27 10:58:26 CST 2016
     */
    int deleteByExample(TeamResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_team_result
     *
     * @mbggenerated Wed Jan 27 10:58:26 CST 2016
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_team_result
     *
     * @mbggenerated Wed Jan 27 10:58:26 CST 2016
     */
    int insert(TeamResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_team_result
     *
     * @mbggenerated Wed Jan 27 10:58:26 CST 2016
     */
    int insertSelective(TeamResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_team_result
     *
     * @mbggenerated Wed Jan 27 10:58:26 CST 2016
     */
    List<TeamResult> selectByExample(TeamResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_team_result
     *
     * @mbggenerated Wed Jan 27 10:58:26 CST 2016
     */
    TeamResult selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_team_result
     *
     * @mbggenerated Wed Jan 27 10:58:26 CST 2016
     */
    int updateByExampleSelective(@Param("record") TeamResult record, @Param("example") TeamResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_team_result
     *
     * @mbggenerated Wed Jan 27 10:58:26 CST 2016
     */
    int updateByExample(@Param("record") TeamResult record, @Param("example") TeamResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_team_result
     *
     * @mbggenerated Wed Jan 27 10:58:26 CST 2016
     */
    int updateByPrimaryKeySelective(TeamResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_team_result
     *
     * @mbggenerated Wed Jan 27 10:58:26 CST 2016
     */
    int updateByPrimaryKey(TeamResult record);
}