package com.tianfang.train.pojo;

import java.util.Date;

public class CompetitionMatch {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition_match.id
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition_match.comp_id
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    private String compId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition_match.comp_name
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    private String compName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition_match.cround_id
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    private String croundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition_match.cround_name
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    private String croundName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition_match.home_team_id
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    private String homeTeamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition_match.home_team_icon
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    private String homeTeamIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition_match.home_team_name
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    private String homeTeamName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition_match.visiting_team_id
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    private String visitingTeamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition_match.visiting_team_icon
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    private String visitingTeamIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition_match.visiting_team_name
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    private String visitingTeamName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition_match.match_type
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    private Integer matchType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition_match.match_time
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    private Date matchTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition_match.home_score
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    private Integer homeScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition_match.visiting_score
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    private Integer visitingScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition_match.address
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition_match.people_type
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    private Integer peopleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition_match.create_admin_id
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    private String createAdminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition_match.create_admin_name
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    private String createAdminName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition_match.create_time
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition_match.last_update_time
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition_match.stat
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition_match.id
     *
     * @return the value of sst_competition_match.id
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition_match.id
     *
     * @param id the value for sst_competition_match.id
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition_match.comp_id
     *
     * @return the value of sst_competition_match.comp_id
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public String getCompId() {
        return compId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition_match.comp_id
     *
     * @param compId the value for sst_competition_match.comp_id
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public void setCompId(String compId) {
        this.compId = compId == null ? null : compId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition_match.comp_name
     *
     * @return the value of sst_competition_match.comp_name
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public String getCompName() {
        return compName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition_match.comp_name
     *
     * @param compName the value for sst_competition_match.comp_name
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public void setCompName(String compName) {
        this.compName = compName == null ? null : compName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition_match.cround_id
     *
     * @return the value of sst_competition_match.cround_id
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public String getCroundId() {
        return croundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition_match.cround_id
     *
     * @param croundId the value for sst_competition_match.cround_id
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public void setCroundId(String croundId) {
        this.croundId = croundId == null ? null : croundId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition_match.cround_name
     *
     * @return the value of sst_competition_match.cround_name
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public String getCroundName() {
        return croundName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition_match.cround_name
     *
     * @param croundName the value for sst_competition_match.cround_name
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public void setCroundName(String croundName) {
        this.croundName = croundName == null ? null : croundName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition_match.home_team_id
     *
     * @return the value of sst_competition_match.home_team_id
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public String getHomeTeamId() {
        return homeTeamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition_match.home_team_id
     *
     * @param homeTeamId the value for sst_competition_match.home_team_id
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public void setHomeTeamId(String homeTeamId) {
        this.homeTeamId = homeTeamId == null ? null : homeTeamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition_match.home_team_icon
     *
     * @return the value of sst_competition_match.home_team_icon
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public String getHomeTeamIcon() {
        return homeTeamIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition_match.home_team_icon
     *
     * @param homeTeamIcon the value for sst_competition_match.home_team_icon
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public void setHomeTeamIcon(String homeTeamIcon) {
        this.homeTeamIcon = homeTeamIcon == null ? null : homeTeamIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition_match.home_team_name
     *
     * @return the value of sst_competition_match.home_team_name
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public String getHomeTeamName() {
        return homeTeamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition_match.home_team_name
     *
     * @param homeTeamName the value for sst_competition_match.home_team_name
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public void setHomeTeamName(String homeTeamName) {
        this.homeTeamName = homeTeamName == null ? null : homeTeamName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition_match.visiting_team_id
     *
     * @return the value of sst_competition_match.visiting_team_id
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public String getVisitingTeamId() {
        return visitingTeamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition_match.visiting_team_id
     *
     * @param visitingTeamId the value for sst_competition_match.visiting_team_id
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public void setVisitingTeamId(String visitingTeamId) {
        this.visitingTeamId = visitingTeamId == null ? null : visitingTeamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition_match.visiting_team_icon
     *
     * @return the value of sst_competition_match.visiting_team_icon
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public String getVisitingTeamIcon() {
        return visitingTeamIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition_match.visiting_team_icon
     *
     * @param visitingTeamIcon the value for sst_competition_match.visiting_team_icon
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public void setVisitingTeamIcon(String visitingTeamIcon) {
        this.visitingTeamIcon = visitingTeamIcon == null ? null : visitingTeamIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition_match.visiting_team_name
     *
     * @return the value of sst_competition_match.visiting_team_name
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public String getVisitingTeamName() {
        return visitingTeamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition_match.visiting_team_name
     *
     * @param visitingTeamName the value for sst_competition_match.visiting_team_name
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public void setVisitingTeamName(String visitingTeamName) {
        this.visitingTeamName = visitingTeamName == null ? null : visitingTeamName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition_match.match_type
     *
     * @return the value of sst_competition_match.match_type
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public Integer getMatchType() {
        return matchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition_match.match_type
     *
     * @param matchType the value for sst_competition_match.match_type
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public void setMatchType(Integer matchType) {
        this.matchType = matchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition_match.match_time
     *
     * @return the value of sst_competition_match.match_time
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public Date getMatchTime() {
        return matchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition_match.match_time
     *
     * @param matchTime the value for sst_competition_match.match_time
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public void setMatchTime(Date matchTime) {
        this.matchTime = matchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition_match.home_score
     *
     * @return the value of sst_competition_match.home_score
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public Integer getHomeScore() {
        return homeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition_match.home_score
     *
     * @param homeScore the value for sst_competition_match.home_score
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public void setHomeScore(Integer homeScore) {
        this.homeScore = homeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition_match.visiting_score
     *
     * @return the value of sst_competition_match.visiting_score
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public Integer getVisitingScore() {
        return visitingScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition_match.visiting_score
     *
     * @param visitingScore the value for sst_competition_match.visiting_score
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public void setVisitingScore(Integer visitingScore) {
        this.visitingScore = visitingScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition_match.address
     *
     * @return the value of sst_competition_match.address
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition_match.address
     *
     * @param address the value for sst_competition_match.address
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition_match.people_type
     *
     * @return the value of sst_competition_match.people_type
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public Integer getPeopleType() {
        return peopleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition_match.people_type
     *
     * @param peopleType the value for sst_competition_match.people_type
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public void setPeopleType(Integer peopleType) {
        this.peopleType = peopleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition_match.create_admin_id
     *
     * @return the value of sst_competition_match.create_admin_id
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public String getCreateAdminId() {
        return createAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition_match.create_admin_id
     *
     * @param createAdminId the value for sst_competition_match.create_admin_id
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public void setCreateAdminId(String createAdminId) {
        this.createAdminId = createAdminId == null ? null : createAdminId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition_match.create_admin_name
     *
     * @return the value of sst_competition_match.create_admin_name
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public String getCreateAdminName() {
        return createAdminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition_match.create_admin_name
     *
     * @param createAdminName the value for sst_competition_match.create_admin_name
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public void setCreateAdminName(String createAdminName) {
        this.createAdminName = createAdminName == null ? null : createAdminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition_match.create_time
     *
     * @return the value of sst_competition_match.create_time
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition_match.create_time
     *
     * @param createTime the value for sst_competition_match.create_time
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition_match.last_update_time
     *
     * @return the value of sst_competition_match.last_update_time
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition_match.last_update_time
     *
     * @param lastUpdateTime the value for sst_competition_match.last_update_time
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition_match.stat
     *
     * @return the value of sst_competition_match.stat
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition_match.stat
     *
     * @param stat the value for sst_competition_match.stat
     *
     * @mbggenerated Tue Feb 23 13:57:02 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}