package com.tianfang.train.pojo;

import java.util.Date;

public class Competition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition.id
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition.title
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition.content
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition.icon
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition.start_date
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition.end_date
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition.is_closed
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    private Integer isClosed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition.comp_type
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    private Integer compType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition.create_admin_id
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    private String createAdminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition.create_admin_name
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    private String createAdminName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition.update_admin_id
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    private String updateAdminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition.update_admin_name
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    private String updateAdminName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition.create_time
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition.last_update_time
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_competition.stat
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition.id
     *
     * @return the value of sst_competition.id
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition.id
     *
     * @param id the value for sst_competition.id
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition.title
     *
     * @return the value of sst_competition.title
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition.title
     *
     * @param title the value for sst_competition.title
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition.content
     *
     * @return the value of sst_competition.content
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition.content
     *
     * @param content the value for sst_competition.content
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition.icon
     *
     * @return the value of sst_competition.icon
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition.icon
     *
     * @param icon the value for sst_competition.icon
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition.start_date
     *
     * @return the value of sst_competition.start_date
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition.start_date
     *
     * @param startDate the value for sst_competition.start_date
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition.end_date
     *
     * @return the value of sst_competition.end_date
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition.end_date
     *
     * @param endDate the value for sst_competition.end_date
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition.is_closed
     *
     * @return the value of sst_competition.is_closed
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public Integer getIsClosed() {
        return isClosed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition.is_closed
     *
     * @param isClosed the value for sst_competition.is_closed
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public void setIsClosed(Integer isClosed) {
        this.isClosed = isClosed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition.comp_type
     *
     * @return the value of sst_competition.comp_type
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public Integer getCompType() {
        return compType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition.comp_type
     *
     * @param compType the value for sst_competition.comp_type
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public void setCompType(Integer compType) {
        this.compType = compType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition.create_admin_id
     *
     * @return the value of sst_competition.create_admin_id
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public String getCreateAdminId() {
        return createAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition.create_admin_id
     *
     * @param createAdminId the value for sst_competition.create_admin_id
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public void setCreateAdminId(String createAdminId) {
        this.createAdminId = createAdminId == null ? null : createAdminId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition.create_admin_name
     *
     * @return the value of sst_competition.create_admin_name
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public String getCreateAdminName() {
        return createAdminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition.create_admin_name
     *
     * @param createAdminName the value for sst_competition.create_admin_name
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public void setCreateAdminName(String createAdminName) {
        this.createAdminName = createAdminName == null ? null : createAdminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition.update_admin_id
     *
     * @return the value of sst_competition.update_admin_id
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public String getUpdateAdminId() {
        return updateAdminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition.update_admin_id
     *
     * @param updateAdminId the value for sst_competition.update_admin_id
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public void setUpdateAdminId(String updateAdminId) {
        this.updateAdminId = updateAdminId == null ? null : updateAdminId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition.update_admin_name
     *
     * @return the value of sst_competition.update_admin_name
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public String getUpdateAdminName() {
        return updateAdminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition.update_admin_name
     *
     * @param updateAdminName the value for sst_competition.update_admin_name
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public void setUpdateAdminName(String updateAdminName) {
        this.updateAdminName = updateAdminName == null ? null : updateAdminName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition.create_time
     *
     * @return the value of sst_competition.create_time
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition.create_time
     *
     * @param createTime the value for sst_competition.create_time
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition.last_update_time
     *
     * @return the value of sst_competition.last_update_time
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition.last_update_time
     *
     * @param lastUpdateTime the value for sst_competition.last_update_time
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_competition.stat
     *
     * @return the value of sst_competition.stat
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_competition.stat
     *
     * @param stat the value for sst_competition.stat
     *
     * @mbggenerated Thu Jan 28 11:42:26 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}