package com.tianfang.train.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MatchPlayerBaseDatasExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    public MatchPlayerBaseDatasExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMatchIdIsNull() {
            addCriterion("match_id is null");
            return (Criteria) this;
        }

        public Criteria andMatchIdIsNotNull() {
            addCriterion("match_id is not null");
            return (Criteria) this;
        }

        public Criteria andMatchIdEqualTo(String value) {
            addCriterion("match_id =", value, "matchId");
            return (Criteria) this;
        }

        public Criteria andMatchIdNotEqualTo(String value) {
            addCriterion("match_id <>", value, "matchId");
            return (Criteria) this;
        }

        public Criteria andMatchIdGreaterThan(String value) {
            addCriterion("match_id >", value, "matchId");
            return (Criteria) this;
        }

        public Criteria andMatchIdGreaterThanOrEqualTo(String value) {
            addCriterion("match_id >=", value, "matchId");
            return (Criteria) this;
        }

        public Criteria andMatchIdLessThan(String value) {
            addCriterion("match_id <", value, "matchId");
            return (Criteria) this;
        }

        public Criteria andMatchIdLessThanOrEqualTo(String value) {
            addCriterion("match_id <=", value, "matchId");
            return (Criteria) this;
        }

        public Criteria andMatchIdLike(String value) {
            addCriterion("match_id like", value, "matchId");
            return (Criteria) this;
        }

        public Criteria andMatchIdNotLike(String value) {
            addCriterion("match_id not like", value, "matchId");
            return (Criteria) this;
        }

        public Criteria andMatchIdIn(List<String> values) {
            addCriterion("match_id in", values, "matchId");
            return (Criteria) this;
        }

        public Criteria andMatchIdNotIn(List<String> values) {
            addCriterion("match_id not in", values, "matchId");
            return (Criteria) this;
        }

        public Criteria andMatchIdBetween(String value1, String value2) {
            addCriterion("match_id between", value1, value2, "matchId");
            return (Criteria) this;
        }

        public Criteria andMatchIdNotBetween(String value1, String value2) {
            addCriterion("match_id not between", value1, value2, "matchId");
            return (Criteria) this;
        }

        public Criteria andTeamIdIsNull() {
            addCriterion("team_id is null");
            return (Criteria) this;
        }

        public Criteria andTeamIdIsNotNull() {
            addCriterion("team_id is not null");
            return (Criteria) this;
        }

        public Criteria andTeamIdEqualTo(String value) {
            addCriterion("team_id =", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdNotEqualTo(String value) {
            addCriterion("team_id <>", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdGreaterThan(String value) {
            addCriterion("team_id >", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdGreaterThanOrEqualTo(String value) {
            addCriterion("team_id >=", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdLessThan(String value) {
            addCriterion("team_id <", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdLessThanOrEqualTo(String value) {
            addCriterion("team_id <=", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdLike(String value) {
            addCriterion("team_id like", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdNotLike(String value) {
            addCriterion("team_id not like", value, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdIn(List<String> values) {
            addCriterion("team_id in", values, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdNotIn(List<String> values) {
            addCriterion("team_id not in", values, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdBetween(String value1, String value2) {
            addCriterion("team_id between", value1, value2, "teamId");
            return (Criteria) this;
        }

        public Criteria andTeamIdNotBetween(String value1, String value2) {
            addCriterion("team_id not between", value1, value2, "teamId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdIsNull() {
            addCriterion("player_id is null");
            return (Criteria) this;
        }

        public Criteria andPlayerIdIsNotNull() {
            addCriterion("player_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlayerIdEqualTo(String value) {
            addCriterion("player_id =", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdNotEqualTo(String value) {
            addCriterion("player_id <>", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdGreaterThan(String value) {
            addCriterion("player_id >", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdGreaterThanOrEqualTo(String value) {
            addCriterion("player_id >=", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdLessThan(String value) {
            addCriterion("player_id <", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdLessThanOrEqualTo(String value) {
            addCriterion("player_id <=", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdLike(String value) {
            addCriterion("player_id like", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdNotLike(String value) {
            addCriterion("player_id not like", value, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdIn(List<String> values) {
            addCriterion("player_id in", values, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdNotIn(List<String> values) {
            addCriterion("player_id not in", values, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdBetween(String value1, String value2) {
            addCriterion("player_id between", value1, value2, "playerId");
            return (Criteria) this;
        }

        public Criteria andPlayerIdNotBetween(String value1, String value2) {
            addCriterion("player_id not between", value1, value2, "playerId");
            return (Criteria) this;
        }

        public Criteria andMinuteIsNull() {
            addCriterion("minute is null");
            return (Criteria) this;
        }

        public Criteria andMinuteIsNotNull() {
            addCriterion("minute is not null");
            return (Criteria) this;
        }

        public Criteria andMinuteEqualTo(Integer value) {
            addCriterion("minute =", value, "minute");
            return (Criteria) this;
        }

        public Criteria andMinuteNotEqualTo(Integer value) {
            addCriterion("minute <>", value, "minute");
            return (Criteria) this;
        }

        public Criteria andMinuteGreaterThan(Integer value) {
            addCriterion("minute >", value, "minute");
            return (Criteria) this;
        }

        public Criteria andMinuteGreaterThanOrEqualTo(Integer value) {
            addCriterion("minute >=", value, "minute");
            return (Criteria) this;
        }

        public Criteria andMinuteLessThan(Integer value) {
            addCriterion("minute <", value, "minute");
            return (Criteria) this;
        }

        public Criteria andMinuteLessThanOrEqualTo(Integer value) {
            addCriterion("minute <=", value, "minute");
            return (Criteria) this;
        }

        public Criteria andMinuteIn(List<Integer> values) {
            addCriterion("minute in", values, "minute");
            return (Criteria) this;
        }

        public Criteria andMinuteNotIn(List<Integer> values) {
            addCriterion("minute not in", values, "minute");
            return (Criteria) this;
        }

        public Criteria andMinuteBetween(Integer value1, Integer value2) {
            addCriterion("minute between", value1, value2, "minute");
            return (Criteria) this;
        }

        public Criteria andMinuteNotBetween(Integer value1, Integer value2) {
            addCriterion("minute not between", value1, value2, "minute");
            return (Criteria) this;
        }

        public Criteria andGoalIsNull() {
            addCriterion("goal is null");
            return (Criteria) this;
        }

        public Criteria andGoalIsNotNull() {
            addCriterion("goal is not null");
            return (Criteria) this;
        }

        public Criteria andGoalEqualTo(Integer value) {
            addCriterion("goal =", value, "goal");
            return (Criteria) this;
        }

        public Criteria andGoalNotEqualTo(Integer value) {
            addCriterion("goal <>", value, "goal");
            return (Criteria) this;
        }

        public Criteria andGoalGreaterThan(Integer value) {
            addCriterion("goal >", value, "goal");
            return (Criteria) this;
        }

        public Criteria andGoalGreaterThanOrEqualTo(Integer value) {
            addCriterion("goal >=", value, "goal");
            return (Criteria) this;
        }

        public Criteria andGoalLessThan(Integer value) {
            addCriterion("goal <", value, "goal");
            return (Criteria) this;
        }

        public Criteria andGoalLessThanOrEqualTo(Integer value) {
            addCriterion("goal <=", value, "goal");
            return (Criteria) this;
        }

        public Criteria andGoalIn(List<Integer> values) {
            addCriterion("goal in", values, "goal");
            return (Criteria) this;
        }

        public Criteria andGoalNotIn(List<Integer> values) {
            addCriterion("goal not in", values, "goal");
            return (Criteria) this;
        }

        public Criteria andGoalBetween(Integer value1, Integer value2) {
            addCriterion("goal between", value1, value2, "goal");
            return (Criteria) this;
        }

        public Criteria andGoalNotBetween(Integer value1, Integer value2) {
            addCriterion("goal not between", value1, value2, "goal");
            return (Criteria) this;
        }

        public Criteria andAssistIsNull() {
            addCriterion("assist is null");
            return (Criteria) this;
        }

        public Criteria andAssistIsNotNull() {
            addCriterion("assist is not null");
            return (Criteria) this;
        }

        public Criteria andAssistEqualTo(Integer value) {
            addCriterion("assist =", value, "assist");
            return (Criteria) this;
        }

        public Criteria andAssistNotEqualTo(Integer value) {
            addCriterion("assist <>", value, "assist");
            return (Criteria) this;
        }

        public Criteria andAssistGreaterThan(Integer value) {
            addCriterion("assist >", value, "assist");
            return (Criteria) this;
        }

        public Criteria andAssistGreaterThanOrEqualTo(Integer value) {
            addCriterion("assist >=", value, "assist");
            return (Criteria) this;
        }

        public Criteria andAssistLessThan(Integer value) {
            addCriterion("assist <", value, "assist");
            return (Criteria) this;
        }

        public Criteria andAssistLessThanOrEqualTo(Integer value) {
            addCriterion("assist <=", value, "assist");
            return (Criteria) this;
        }

        public Criteria andAssistIn(List<Integer> values) {
            addCriterion("assist in", values, "assist");
            return (Criteria) this;
        }

        public Criteria andAssistNotIn(List<Integer> values) {
            addCriterion("assist not in", values, "assist");
            return (Criteria) this;
        }

        public Criteria andAssistBetween(Integer value1, Integer value2) {
            addCriterion("assist between", value1, value2, "assist");
            return (Criteria) this;
        }

        public Criteria andAssistNotBetween(Integer value1, Integer value2) {
            addCriterion("assist not between", value1, value2, "assist");
            return (Criteria) this;
        }

        public Criteria andShotIsNull() {
            addCriterion("shot is null");
            return (Criteria) this;
        }

        public Criteria andShotIsNotNull() {
            addCriterion("shot is not null");
            return (Criteria) this;
        }

        public Criteria andShotEqualTo(Integer value) {
            addCriterion("shot =", value, "shot");
            return (Criteria) this;
        }

        public Criteria andShotNotEqualTo(Integer value) {
            addCriterion("shot <>", value, "shot");
            return (Criteria) this;
        }

        public Criteria andShotGreaterThan(Integer value) {
            addCriterion("shot >", value, "shot");
            return (Criteria) this;
        }

        public Criteria andShotGreaterThanOrEqualTo(Integer value) {
            addCriterion("shot >=", value, "shot");
            return (Criteria) this;
        }

        public Criteria andShotLessThan(Integer value) {
            addCriterion("shot <", value, "shot");
            return (Criteria) this;
        }

        public Criteria andShotLessThanOrEqualTo(Integer value) {
            addCriterion("shot <=", value, "shot");
            return (Criteria) this;
        }

        public Criteria andShotIn(List<Integer> values) {
            addCriterion("shot in", values, "shot");
            return (Criteria) this;
        }

        public Criteria andShotNotIn(List<Integer> values) {
            addCriterion("shot not in", values, "shot");
            return (Criteria) this;
        }

        public Criteria andShotBetween(Integer value1, Integer value2) {
            addCriterion("shot between", value1, value2, "shot");
            return (Criteria) this;
        }

        public Criteria andShotNotBetween(Integer value1, Integer value2) {
            addCriterion("shot not between", value1, value2, "shot");
            return (Criteria) this;
        }

        public Criteria andShotRightIsNull() {
            addCriterion("shot_right is null");
            return (Criteria) this;
        }

        public Criteria andShotRightIsNotNull() {
            addCriterion("shot_right is not null");
            return (Criteria) this;
        }

        public Criteria andShotRightEqualTo(Integer value) {
            addCriterion("shot_right =", value, "shotRight");
            return (Criteria) this;
        }

        public Criteria andShotRightNotEqualTo(Integer value) {
            addCriterion("shot_right <>", value, "shotRight");
            return (Criteria) this;
        }

        public Criteria andShotRightGreaterThan(Integer value) {
            addCriterion("shot_right >", value, "shotRight");
            return (Criteria) this;
        }

        public Criteria andShotRightGreaterThanOrEqualTo(Integer value) {
            addCriterion("shot_right >=", value, "shotRight");
            return (Criteria) this;
        }

        public Criteria andShotRightLessThan(Integer value) {
            addCriterion("shot_right <", value, "shotRight");
            return (Criteria) this;
        }

        public Criteria andShotRightLessThanOrEqualTo(Integer value) {
            addCriterion("shot_right <=", value, "shotRight");
            return (Criteria) this;
        }

        public Criteria andShotRightIn(List<Integer> values) {
            addCriterion("shot_right in", values, "shotRight");
            return (Criteria) this;
        }

        public Criteria andShotRightNotIn(List<Integer> values) {
            addCriterion("shot_right not in", values, "shotRight");
            return (Criteria) this;
        }

        public Criteria andShotRightBetween(Integer value1, Integer value2) {
            addCriterion("shot_right between", value1, value2, "shotRight");
            return (Criteria) this;
        }

        public Criteria andShotRightNotBetween(Integer value1, Integer value2) {
            addCriterion("shot_right not between", value1, value2, "shotRight");
            return (Criteria) this;
        }

        public Criteria andPassIsNull() {
            addCriterion("pass is null");
            return (Criteria) this;
        }

        public Criteria andPassIsNotNull() {
            addCriterion("pass is not null");
            return (Criteria) this;
        }

        public Criteria andPassEqualTo(Integer value) {
            addCriterion("pass =", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassNotEqualTo(Integer value) {
            addCriterion("pass <>", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassGreaterThan(Integer value) {
            addCriterion("pass >", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassGreaterThanOrEqualTo(Integer value) {
            addCriterion("pass >=", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassLessThan(Integer value) {
            addCriterion("pass <", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassLessThanOrEqualTo(Integer value) {
            addCriterion("pass <=", value, "pass");
            return (Criteria) this;
        }

        public Criteria andPassIn(List<Integer> values) {
            addCriterion("pass in", values, "pass");
            return (Criteria) this;
        }

        public Criteria andPassNotIn(List<Integer> values) {
            addCriterion("pass not in", values, "pass");
            return (Criteria) this;
        }

        public Criteria andPassBetween(Integer value1, Integer value2) {
            addCriterion("pass between", value1, value2, "pass");
            return (Criteria) this;
        }

        public Criteria andPassNotBetween(Integer value1, Integer value2) {
            addCriterion("pass not between", value1, value2, "pass");
            return (Criteria) this;
        }

        public Criteria andFoulIsNull() {
            addCriterion("foul is null");
            return (Criteria) this;
        }

        public Criteria andFoulIsNotNull() {
            addCriterion("foul is not null");
            return (Criteria) this;
        }

        public Criteria andFoulEqualTo(Integer value) {
            addCriterion("foul =", value, "foul");
            return (Criteria) this;
        }

        public Criteria andFoulNotEqualTo(Integer value) {
            addCriterion("foul <>", value, "foul");
            return (Criteria) this;
        }

        public Criteria andFoulGreaterThan(Integer value) {
            addCriterion("foul >", value, "foul");
            return (Criteria) this;
        }

        public Criteria andFoulGreaterThanOrEqualTo(Integer value) {
            addCriterion("foul >=", value, "foul");
            return (Criteria) this;
        }

        public Criteria andFoulLessThan(Integer value) {
            addCriterion("foul <", value, "foul");
            return (Criteria) this;
        }

        public Criteria andFoulLessThanOrEqualTo(Integer value) {
            addCriterion("foul <=", value, "foul");
            return (Criteria) this;
        }

        public Criteria andFoulIn(List<Integer> values) {
            addCriterion("foul in", values, "foul");
            return (Criteria) this;
        }

        public Criteria andFoulNotIn(List<Integer> values) {
            addCriterion("foul not in", values, "foul");
            return (Criteria) this;
        }

        public Criteria andFoulBetween(Integer value1, Integer value2) {
            addCriterion("foul between", value1, value2, "foul");
            return (Criteria) this;
        }

        public Criteria andFoulNotBetween(Integer value1, Integer value2) {
            addCriterion("foul not between", value1, value2, "foul");
            return (Criteria) this;
        }

        public Criteria andTackleIsNull() {
            addCriterion("tackle is null");
            return (Criteria) this;
        }

        public Criteria andTackleIsNotNull() {
            addCriterion("tackle is not null");
            return (Criteria) this;
        }

        public Criteria andTackleEqualTo(Integer value) {
            addCriterion("tackle =", value, "tackle");
            return (Criteria) this;
        }

        public Criteria andTackleNotEqualTo(Integer value) {
            addCriterion("tackle <>", value, "tackle");
            return (Criteria) this;
        }

        public Criteria andTackleGreaterThan(Integer value) {
            addCriterion("tackle >", value, "tackle");
            return (Criteria) this;
        }

        public Criteria andTackleGreaterThanOrEqualTo(Integer value) {
            addCriterion("tackle >=", value, "tackle");
            return (Criteria) this;
        }

        public Criteria andTackleLessThan(Integer value) {
            addCriterion("tackle <", value, "tackle");
            return (Criteria) this;
        }

        public Criteria andTackleLessThanOrEqualTo(Integer value) {
            addCriterion("tackle <=", value, "tackle");
            return (Criteria) this;
        }

        public Criteria andTackleIn(List<Integer> values) {
            addCriterion("tackle in", values, "tackle");
            return (Criteria) this;
        }

        public Criteria andTackleNotIn(List<Integer> values) {
            addCriterion("tackle not in", values, "tackle");
            return (Criteria) this;
        }

        public Criteria andTackleBetween(Integer value1, Integer value2) {
            addCriterion("tackle between", value1, value2, "tackle");
            return (Criteria) this;
        }

        public Criteria andTackleNotBetween(Integer value1, Integer value2) {
            addCriterion("tackle not between", value1, value2, "tackle");
            return (Criteria) this;
        }

        public Criteria andClearanceKickIsNull() {
            addCriterion("clearance_kick is null");
            return (Criteria) this;
        }

        public Criteria andClearanceKickIsNotNull() {
            addCriterion("clearance_kick is not null");
            return (Criteria) this;
        }

        public Criteria andClearanceKickEqualTo(Integer value) {
            addCriterion("clearance_kick =", value, "clearanceKick");
            return (Criteria) this;
        }

        public Criteria andClearanceKickNotEqualTo(Integer value) {
            addCriterion("clearance_kick <>", value, "clearanceKick");
            return (Criteria) this;
        }

        public Criteria andClearanceKickGreaterThan(Integer value) {
            addCriterion("clearance_kick >", value, "clearanceKick");
            return (Criteria) this;
        }

        public Criteria andClearanceKickGreaterThanOrEqualTo(Integer value) {
            addCriterion("clearance_kick >=", value, "clearanceKick");
            return (Criteria) this;
        }

        public Criteria andClearanceKickLessThan(Integer value) {
            addCriterion("clearance_kick <", value, "clearanceKick");
            return (Criteria) this;
        }

        public Criteria andClearanceKickLessThanOrEqualTo(Integer value) {
            addCriterion("clearance_kick <=", value, "clearanceKick");
            return (Criteria) this;
        }

        public Criteria andClearanceKickIn(List<Integer> values) {
            addCriterion("clearance_kick in", values, "clearanceKick");
            return (Criteria) this;
        }

        public Criteria andClearanceKickNotIn(List<Integer> values) {
            addCriterion("clearance_kick not in", values, "clearanceKick");
            return (Criteria) this;
        }

        public Criteria andClearanceKickBetween(Integer value1, Integer value2) {
            addCriterion("clearance_kick between", value1, value2, "clearanceKick");
            return (Criteria) this;
        }

        public Criteria andClearanceKickNotBetween(Integer value1, Integer value2) {
            addCriterion("clearance_kick not between", value1, value2, "clearanceKick");
            return (Criteria) this;
        }

        public Criteria andSaveIsNull() {
            addCriterion("save is null");
            return (Criteria) this;
        }

        public Criteria andSaveIsNotNull() {
            addCriterion("save is not null");
            return (Criteria) this;
        }

        public Criteria andSaveEqualTo(Integer value) {
            addCriterion("save =", value, "save");
            return (Criteria) this;
        }

        public Criteria andSaveNotEqualTo(Integer value) {
            addCriterion("save <>", value, "save");
            return (Criteria) this;
        }

        public Criteria andSaveGreaterThan(Integer value) {
            addCriterion("save >", value, "save");
            return (Criteria) this;
        }

        public Criteria andSaveGreaterThanOrEqualTo(Integer value) {
            addCriterion("save >=", value, "save");
            return (Criteria) this;
        }

        public Criteria andSaveLessThan(Integer value) {
            addCriterion("save <", value, "save");
            return (Criteria) this;
        }

        public Criteria andSaveLessThanOrEqualTo(Integer value) {
            addCriterion("save <=", value, "save");
            return (Criteria) this;
        }

        public Criteria andSaveIn(List<Integer> values) {
            addCriterion("save in", values, "save");
            return (Criteria) this;
        }

        public Criteria andSaveNotIn(List<Integer> values) {
            addCriterion("save not in", values, "save");
            return (Criteria) this;
        }

        public Criteria andSaveBetween(Integer value1, Integer value2) {
            addCriterion("save between", value1, value2, "save");
            return (Criteria) this;
        }

        public Criteria andSaveNotBetween(Integer value1, Integer value2) {
            addCriterion("save not between", value1, value2, "save");
            return (Criteria) this;
        }

        public Criteria andYellowIsNull() {
            addCriterion("yellow is null");
            return (Criteria) this;
        }

        public Criteria andYellowIsNotNull() {
            addCriterion("yellow is not null");
            return (Criteria) this;
        }

        public Criteria andYellowEqualTo(Integer value) {
            addCriterion("yellow =", value, "yellow");
            return (Criteria) this;
        }

        public Criteria andYellowNotEqualTo(Integer value) {
            addCriterion("yellow <>", value, "yellow");
            return (Criteria) this;
        }

        public Criteria andYellowGreaterThan(Integer value) {
            addCriterion("yellow >", value, "yellow");
            return (Criteria) this;
        }

        public Criteria andYellowGreaterThanOrEqualTo(Integer value) {
            addCriterion("yellow >=", value, "yellow");
            return (Criteria) this;
        }

        public Criteria andYellowLessThan(Integer value) {
            addCriterion("yellow <", value, "yellow");
            return (Criteria) this;
        }

        public Criteria andYellowLessThanOrEqualTo(Integer value) {
            addCriterion("yellow <=", value, "yellow");
            return (Criteria) this;
        }

        public Criteria andYellowIn(List<Integer> values) {
            addCriterion("yellow in", values, "yellow");
            return (Criteria) this;
        }

        public Criteria andYellowNotIn(List<Integer> values) {
            addCriterion("yellow not in", values, "yellow");
            return (Criteria) this;
        }

        public Criteria andYellowBetween(Integer value1, Integer value2) {
            addCriterion("yellow between", value1, value2, "yellow");
            return (Criteria) this;
        }

        public Criteria andYellowNotBetween(Integer value1, Integer value2) {
            addCriterion("yellow not between", value1, value2, "yellow");
            return (Criteria) this;
        }

        public Criteria andRedIsNull() {
            addCriterion("red is null");
            return (Criteria) this;
        }

        public Criteria andRedIsNotNull() {
            addCriterion("red is not null");
            return (Criteria) this;
        }

        public Criteria andRedEqualTo(Integer value) {
            addCriterion("red =", value, "red");
            return (Criteria) this;
        }

        public Criteria andRedNotEqualTo(Integer value) {
            addCriterion("red <>", value, "red");
            return (Criteria) this;
        }

        public Criteria andRedGreaterThan(Integer value) {
            addCriterion("red >", value, "red");
            return (Criteria) this;
        }

        public Criteria andRedGreaterThanOrEqualTo(Integer value) {
            addCriterion("red >=", value, "red");
            return (Criteria) this;
        }

        public Criteria andRedLessThan(Integer value) {
            addCriterion("red <", value, "red");
            return (Criteria) this;
        }

        public Criteria andRedLessThanOrEqualTo(Integer value) {
            addCriterion("red <=", value, "red");
            return (Criteria) this;
        }

        public Criteria andRedIn(List<Integer> values) {
            addCriterion("red in", values, "red");
            return (Criteria) this;
        }

        public Criteria andRedNotIn(List<Integer> values) {
            addCriterion("red not in", values, "red");
            return (Criteria) this;
        }

        public Criteria andRedBetween(Integer value1, Integer value2) {
            addCriterion("red between", value1, value2, "red");
            return (Criteria) this;
        }

        public Criteria andRedNotBetween(Integer value1, Integer value2) {
            addCriterion("red not between", value1, value2, "red");
            return (Criteria) this;
        }

        public Criteria andReserveIsNull() {
            addCriterion("reserve is null");
            return (Criteria) this;
        }

        public Criteria andReserveIsNotNull() {
            addCriterion("reserve is not null");
            return (Criteria) this;
        }

        public Criteria andReserveEqualTo(Integer value) {
            addCriterion("reserve =", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveNotEqualTo(Integer value) {
            addCriterion("reserve <>", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveGreaterThan(Integer value) {
            addCriterion("reserve >", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveGreaterThanOrEqualTo(Integer value) {
            addCriterion("reserve >=", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveLessThan(Integer value) {
            addCriterion("reserve <", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveLessThanOrEqualTo(Integer value) {
            addCriterion("reserve <=", value, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveIn(List<Integer> values) {
            addCriterion("reserve in", values, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveNotIn(List<Integer> values) {
            addCriterion("reserve not in", values, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveBetween(Integer value1, Integer value2) {
            addCriterion("reserve between", value1, value2, "reserve");
            return (Criteria) this;
        }

        public Criteria andReserveNotBetween(Integer value1, Integer value2) {
            addCriterion("reserve not between", value1, value2, "reserve");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNull() {
            addCriterion("last_update_time is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIsNotNull() {
            addCriterion("last_update_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeEqualTo(Date value) {
            addCriterion("last_update_time =", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotEqualTo(Date value) {
            addCriterion("last_update_time <>", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThan(Date value) {
            addCriterion("last_update_time >", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_update_time >=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThan(Date value) {
            addCriterion("last_update_time <", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_update_time <=", value, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeIn(List<Date> values) {
            addCriterion("last_update_time in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotIn(List<Date> values) {
            addCriterion("last_update_time not in", values, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("last_update_time between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andLastUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_update_time not between", value1, value2, "lastUpdateTime");
            return (Criteria) this;
        }

        public Criteria andStatIsNull() {
            addCriterion("stat is null");
            return (Criteria) this;
        }

        public Criteria andStatIsNotNull() {
            addCriterion("stat is not null");
            return (Criteria) this;
        }

        public Criteria andStatEqualTo(Integer value) {
            addCriterion("stat =", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotEqualTo(Integer value) {
            addCriterion("stat <>", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThan(Integer value) {
            addCriterion("stat >", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatGreaterThanOrEqualTo(Integer value) {
            addCriterion("stat >=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThan(Integer value) {
            addCriterion("stat <", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatLessThanOrEqualTo(Integer value) {
            addCriterion("stat <=", value, "stat");
            return (Criteria) this;
        }

        public Criteria andStatIn(List<Integer> values) {
            addCriterion("stat in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotIn(List<Integer> values) {
            addCriterion("stat not in", values, "stat");
            return (Criteria) this;
        }

        public Criteria andStatBetween(Integer value1, Integer value2) {
            addCriterion("stat between", value1, value2, "stat");
            return (Criteria) this;
        }

        public Criteria andStatNotBetween(Integer value1, Integer value2) {
            addCriterion("stat not between", value1, value2, "stat");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated do_not_delete_during_merge Tue Mar 22 13:17:19 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sst_match_player_base_datas
     *
     * @mbggenerated Tue Mar 22 13:17:19 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}