package com.tianfang.train.pojo;

import java.util.Date;

public class Team {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_team.id
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_team.name
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_team.icon
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    private String icon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_team.province
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_team.city
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_team.area
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_team.address
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_team.summary
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    private String summary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_team.contacts
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    private String contacts;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_team.mobile
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_team.create_user_id
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_team.create_user_name
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    private String createUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_team.update_user_id
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_team.update_user_name
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    private String updateUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_team.create_time
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_team.last_update_time
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sst_team.stat
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    private Integer stat;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_team.id
     *
     * @return the value of sst_team.id
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_team.id
     *
     * @param id the value for sst_team.id
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_team.name
     *
     * @return the value of sst_team.name
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_team.name
     *
     * @param name the value for sst_team.name
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_team.icon
     *
     * @return the value of sst_team.icon
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_team.icon
     *
     * @param icon the value for sst_team.icon
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_team.province
     *
     * @return the value of sst_team.province
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_team.province
     *
     * @param province the value for sst_team.province
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_team.city
     *
     * @return the value of sst_team.city
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_team.city
     *
     * @param city the value for sst_team.city
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_team.area
     *
     * @return the value of sst_team.area
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_team.area
     *
     * @param area the value for sst_team.area
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_team.address
     *
     * @return the value of sst_team.address
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_team.address
     *
     * @param address the value for sst_team.address
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_team.summary
     *
     * @return the value of sst_team.summary
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_team.summary
     *
     * @param summary the value for sst_team.summary
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_team.contacts
     *
     * @return the value of sst_team.contacts
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public String getContacts() {
        return contacts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_team.contacts
     *
     * @param contacts the value for sst_team.contacts
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public void setContacts(String contacts) {
        this.contacts = contacts == null ? null : contacts.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_team.mobile
     *
     * @return the value of sst_team.mobile
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_team.mobile
     *
     * @param mobile the value for sst_team.mobile
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_team.create_user_id
     *
     * @return the value of sst_team.create_user_id
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_team.create_user_id
     *
     * @param createUserId the value for sst_team.create_user_id
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_team.create_user_name
     *
     * @return the value of sst_team.create_user_name
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_team.create_user_name
     *
     * @param createUserName the value for sst_team.create_user_name
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_team.update_user_id
     *
     * @return the value of sst_team.update_user_id
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_team.update_user_id
     *
     * @param updateUserId the value for sst_team.update_user_id
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId == null ? null : updateUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_team.update_user_name
     *
     * @return the value of sst_team.update_user_name
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public String getUpdateUserName() {
        return updateUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_team.update_user_name
     *
     * @param updateUserName the value for sst_team.update_user_name
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public void setUpdateUserName(String updateUserName) {
        this.updateUserName = updateUserName == null ? null : updateUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_team.create_time
     *
     * @return the value of sst_team.create_time
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_team.create_time
     *
     * @param createTime the value for sst_team.create_time
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_team.last_update_time
     *
     * @return the value of sst_team.last_update_time
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_team.last_update_time
     *
     * @param lastUpdateTime the value for sst_team.last_update_time
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sst_team.stat
     *
     * @return the value of sst_team.stat
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public Integer getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sst_team.stat
     *
     * @param stat the value for sst_team.stat
     *
     * @mbggenerated Sat Jan 23 10:22:36 CST 2016
     */
    public void setStat(Integer stat) {
        this.stat = stat;
    }
}